### PR TITLE
Additional frames

### PR DESCRIPTION
**Pull request by NCrusher74**
So basically I sort of went back to the drawing board, and in some ways it was successful and in other ways it wasn't.

Success: Some other apps (MediaInfo and Kid3) are now reading the `ITunesCompilation` frame as intended. Or at least, they're reading it, period, and displaying "true" as the value.

However, Music will no longer open the file, so that's a bit of a problem.

### CODE REVIEW

**Comment by NCrusher74** [comment]
I changed things up so that the frame should be 

Well, pretty much everything is reading the file properly now EXCEPT for Music. A metadata writer that produces a file that won't be handled by the most ubiquitous app probably isn't a good thing.

This is what I'm seeing now when I read the bytes from the file that Yate wrote: 

`54 43 4d 50 0 0 0 2 0 0 0 31`

According to the translator I found, those first four are "TCMP" which is the frameIdentifier for the Compilation frame. But I'm not sure I'm using the right translator because the rest comes out as gibberish, even when taken in 4-byte pieces.

I have a few frame creator tests that are failing under this new way of handling it, mainly because I'm not sure if the bytes the test starts with have anything to do with what I'm working on.

**Comment by SDGGiesbrecht** [comment]
> the rest comes out as gibberish

Only the parts that are strings will be decodable as strings. The rest are other kinds of binary data.

The first four are the tag name `"TCMP"`, as you figured out. The next four are the size of the frame i.e. `2` bytes (with leading zeroes). The next two are empty flag bytes. That accounts for the header common to all frames.

Then come the 2 bytes of the frame’s contents. The first is empty, the second contains the _string_ `"1"`. So is it supposed to be a _string_ that contains the digit one, or is it supposed to be a one‐byte _integer_ containing the number 1? i.e. `0x01`? I understood the latter from what you you wrote before, which is why I had you interpreting `0x00` for `false` and `0x01` for `true`. But if it is supposed to be a _string_, then `0x30` (`"0"`) would be `false` and `0x31` (`"1"`) would be `true`.

**Comment by NCrusher74** [comment]
The reason I went with the latter at first was because of the of the `TagLib` implementation of the Podcast frame (it doesn't have a compilation frame), which is described in the comments as:

```
    /*!
     * An implementation of ID3v2 podcast flag, a frame with four zero bytes.
     */
```

I assumed the Compilation frame would be the same because an app called mp3tag handles the two identically.

However, the ID3.org documentation of the *Compilation* frame is as follows:

```
TCMP - iTunes Compilation Flag (class 4)

This is a simple text frame that iTunes uses to indicate if the file is part of a compilation.

 Information
     1 if part of a compilation
     0 or not present if not part of a compilation
```
and I sort of missed the part it being a text frame because I was focused on how TagLib had described the Podcast frame--which ID3 org doesn't have any documentation on.

Considering that Yate didn't recognize what I was doing with the Compilation frame until I made it the String "1", I'm going to hazard a guess that that's what Yate does. Other apps seem to be more or less forgiving (Kid3 read it when it was being returned as the string "true" and MediaInfo read "true" and interprets "1" as "Yes").

Since literally none of these apps is handling the Podcast frame as it exists (Kid3 knows *something* is there but doesn't recognize what, and Yate seems willing to change the `Media Type` frame to "Podcast" if *anything* is written to the Podcast frame) maybe my mistake has been in assuming the two should be handled identically?

Music read the file when I was writing a single byte (0x01) to both of them, but it wasn't interpreting the Compilation frame correctly.

So maybe my next attempt should be to handle the Compilation frame as a single-byte string of 0 or 1, and the Podcast frame as a single integer byte?

**Comment by NCrusher74** [comment]
Okay, it's definitely the Podcast frame causing Music not to like the file, because I wrote a file without that one frame and it worked fine. I wonder if it's deprecated since ITunes split up into all those different apps, because Music no longer offers any options except "music" in the dropdown where once there would have been "podcast" and "audiobooks" and so forth.

It reads Yate files marked as podcasts, but that's because Yate doesn't use the PCST frame, it just uses the MediaType frame, and Music ignores that if it's not "music."

So I guess I'll just get rid of the Podcast frame altogether. Its function is effectively negated by the existence of the Media Type frame anyway, and every other app seems to prefer that frame.

**Comment by NCrusher74** [comment]
Okay, all my tests are passing and everything appears to be playing nicely with other apps, so I'm going to merge this branch and start a different branch for the rest of the frame implementations I want to do.

The next pair of frames I implement may be a little tricker (I'm saving CTOC and CHAP for last, so those will be the frames AFTER this next pair of frames.) It's the "Involved Persons List" and "Musician Credits List" frames, and depending on how you read the specs from ID3.org, the implementation may differ from `.version3` to `.version4`. That'll be fun.

**Pull request merged**
