### PR TITLE
Issues with acceptance test

### PR DESCRIPTION
**Pull request by NCrusher74**
So, in the process of looking over `ID3TagEditor` to see about fixing that issue with the dictionary, I got sidetracked by the fact that I still hadn't implemented the rest of the ID3 frames, including some that I think I'll probably want to use down the road (not in `AudiobookTagger`, but because `AudiobookTagger` is so narrow in the scope of its focus, I think I may make a variation of it (the `SwiftTagger` idea I was messing around with last week) that is aimed more at all sorts of non-music, spoken-word media, like podcasts and so forth, to which music tags don't always apply but some of the tags usually found in visual media like TV shows, etc, do.)

So I decided while I was back to working on expanding `ID3TagEditor` I might as well add those. But I'm running into a little difficulty with the URL frames.

I thought it was going to be fairly straightforward, because it looked like the spec was pretty much identical to the text information frames, but then I noticed one slight difference:

```
4.2.   Text information frames

   The text information frames are often the most important frames,
   containing information like artist, album and more. There may only be
   one text information frame of its kind in an tag. All text
   information frames supports multiple strings, stored as a null
   separated list, where null is reperesented by the termination code
   for the charater encoding. All text frame identifiers begin with "T".
   Only text frame identifiers begin with "T", with the exception of the
   "TXXX" frame. All the text information frames have the following
   format:

     <Header for 'Text information frame', ID: "T000" - "TZZZ",
     excluding "TXXX" described in 4.2.6.>
     Text encoding                $xx
     Information                  <text string(s) according to encoding>
```

versus

```
4.3.   URL link frames

   With these frames dynamic data such as webpages with touring
   information, price information or plain ordinary news can be added to
   the tag. There may only be one URL [URL] link frame of its kind in an
   tag, except when stated otherwise in the frame description. If the
   text string is followed by a string termination, all the following
   information should be ignored and not be displayed. All URL link
   frame identifiers begins with "W". Only URL link frame identifiers
   begins with "W", except for "WXXX". All URL link frames have the
   following format:

     <Header for 'URL link frame', ID: "W000" - "WZZZ", excluding "WXXX"
     described in 4.3.2.>
     URL              <text string>
```

So it looks like the URL frames don't need the encoding byte. Which I think I know what that means, but considering the hash I made of messing with that sort of thing last time, I wanted to seek out your input before I went too far with it.

As it is, this is what the URL's written by what I've implemented look like when viewed in a compliant app:

Screen Shot 2020-03-30 at 1 18 11 PM

And when I run the writing test in the acceptance tests, the final test fails:

Screen Shot 2020-03-30 at 1 50 48 PM

Probably for the same reason that the URL is coming out as gibberish in a compliant viewer. Which is probably that encoding byte being there when it shouldn't be?

The other issue is to do with the WXXX frame.

Again, the wording of the description is so similar that I thought it would work to just use the `ID3FrameUserDefinedText` as you implemented it.

```
4.2.6.   User defined text information frame

   This frame is intended for one-string text information concerning the
   audio file in a similar way to the other "T"-frames. The frame body
   consists of a description of the string, represented as a terminated
   string, followed by the actual string. There may be more than one
   "TXXX" frame in each tag, but only one with the same description.

     <Header for 'User defined text information frame', ID: "TXXX">
     Text encoding     $xx
     Description       <text string according to encoding> $00 (00)
     Value             <text string according to encoding>
```

versus

```
4.3.2.   User defined URL link frame

   This frame is intended for URL [URL] links concerning the audio file
   in a similar way to the other "W"-frames. The frame body consists
   of a description of the string, represented as a terminated string,
   followed by the actual URL. The URL is always encoded with ISO-8859-1
   [ISO-8859-1]. There may be more than one "WXXX" frame in each tag,
   but only one with the same description.

     <Header for 'User defined URL link frame', ID: "WXXX">
     Text encoding     $xx
     Description       <text string according to encoding> $00 (00)
     URL               <text string>

```

And it sort of works. The URL comes out correctly when viewed in Yate or Kid3.

But you also did a lot of stuff with the parsing that I'm clearly not dealing with correctly, because the acceptance test is failing with a nil return on the `FrameParser` extension, and I don't know what it's getting that from.

Screen Shot 2020-03-30 at 1 30 09 PM

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
> So it looks like the URL frames don't need the encoding byte.

Correct. The specification is saying they shouldn’t have one. They also need to be properly encoded as ASCII. The `ÿþ` in Latin 1 is bytewise identical to a byte order mark in UTF‐16.

> But you also did a lot of stuff with the parsing that I'm clearly not dealing with correctly, because the acceptance test is failing with a nil return on the FrameParser extension, and I don't know what it's getting that from.

See `fourByteString` and `threeByteString` and add the necessary entries. That assertion just verifies that the data it has been given really is the kind of frame it is being asked to parse.

**Comment by NCrusher74** [comment]
Okay that latter one was an easy fix. The former is giving me a little more trouble.

If I'm understanding what things are doing correctly, what I need to do is make the `includingEncoding` parameter here `false`, correct?

```swift
extension StringToBytesAdapter {

  internal func adapt(
    string: String,
    for version: ID3Version,
    includingEncoding: Bool = true,
    includingTermination: Bool = true
  ) -> [UInt8] {
    var data = adapt(stringOnly: string)
    if includingEncoding {
      data.insert(contentsOf: encoding(for: version), at: data.startIndex)
    }
    if includingTermination {
      data.append(contentsOf: termination())
    }
    return data
  }
}
```

But I'm not sure where I should handle the ASCII encoding. Or how.

**Comment by NCrusher74** [comment]
I'm guessing here without any real idea of what this means. I added `.ascii` to the `ID3StringEncoding` enum, and then created an `ID3ASCIIStringToByteAdapter`.  But I'm not sure if I should make any more changes to it beside replacing the encoding of the other StringToByte adapters with `.ascii`, like here:

```swift
    func adapt(stringOnly string: String) -> [UInt8] {
        return string.data(using: .ascii).map({ [UInt8]($0) })
        ?? [UInt8](string.utf8)
    }
}
```

**Comment by SDGGiesbrecht** [comment]
> If I'm understanding what things are doing correctly, what I need to do is make the includingEncoding parameter here false, correct?

Correct.

> But I'm not sure where I should handle the ASCII encoding.

The standard library has methods for this (which you found). You can ignore the ID3 configuration, because only one encoding is valid anyway. (If it were me, I wouldn’t even bother with the separate adapter type.)

**Comment by NCrusher74** [comment]
I'm not sure how to do this without a different StringToBytes adapter.

This bit in the `ID3FrameCreatorsChainFactory` is what I would probably copy, substituting my new `ID3FrameFromURLStringContentCreator` for `ID3FrameFromStringContentCreator`, correct?

What would I do instead of referring to the `stringToBytesAdapter`?

```swift
        let frameFromStringISO88591ContentCreator = ID3FrameFromStringContentCreator(
            frameContentSizeCalculator: frameContentSizeCalculator,
            frameFlagsCreator: frameFlagsCreator,
            stringToBytesAdapter: ID3ISO88591StringToByteAdapter(paddingAdder: paddingAdder,
                                                                 frameConfiguration: frameConfiguration)
        )
```

For that matter, I'm not sure how I would tell it to use `.ascii` instead of any of the other options in the encoding enum without the adapter, since that is where that happens, I believe.

**Comment by SDGGiesbrecht** [comment]
You literally just stick `string.data(using: .ascii).map({ [UInt8]($0) }) ?? [UInt8](string.utf8)` in the source at the point you need to convert. Then scrap the adapter altogether. In the other frames, several adapters could be swapped in and out so that the caller could pass an adapter to choose whichever encoding they wanted. But none of that matters here.

**Comment by NCrusher74** [comment]
So, remove the `stringToBytes` adapter as a parameter, and instead of:

```swift
    func createFrame(frameIdentifier: [UInt8], version: ID3Version, content: String) -> [UInt8] {
        var frame: [UInt8] = frameIdentifier
        let contentAsBytes = stringToBytesAdapter.adapt(stringOnly: content)
        frame.append(contentsOf: frameContentSizeCalculator.calculateSizeOf(content: contentAsBytes, version: version))
        frame.append(contentsOf: frameFlagsCreator.createFor(version: version))
        frame.append(contentsOf: contentAsBytes)
        return frame
    }
```

I would use:

```swift

func createFrame(frameIdentifier: [UInt8], version: ID3Version, content: String) -> [UInt8] {
    var frame: [UInt8] = frameIdentifier
    let contentAsBytes = content.data(using: .ascii).map({ [UInt8]($0) }) ?? [UInt8](content.utf8)
    frame.append(contentsOf: frameContentSizeCalculator.calculateSizeOf(content: contentAsBytes, version: version))
    frame.append(contentsOf: frameFlagsCreator.createFor(version: version))
    frame.append(contentsOf: contentAsBytes)
    return frame
}
```

? Am I understanding that correctly?

**Comment by SDGGiesbrecht** [comment]
Yes.

**Comment by NCrusher74** [comment]
Okay, once again I'm lost in the quagmire of parsers and parsing operations and parsing operation factories.

The problem: when reading a URL written by a compliant app, the URL is coming out with the "h" missing from the beginning of the "http://" which is, of course, causing the tests to fail.

I assume this is because, while I THINK the writing will work properly now that I've changed the frame creator, for the URL frames, I haven't yet changed anything about the parsing of the frames, which I assume is where the reading side of things happens?

Until I get the reading hammered out, though, I can't really conduct any writing tests aside from eyeballing the output in another app.

But I still don't know how all these little pieces fit together.

Okay. So I've got my `ID3<whatever>UrlFrameContentParsingOperationFactory` here, as such.

``` swift
class ID3RadioStationUrlFrameContentParsingOperationFactory {
    static func make() -> ID3FrameStringContentParsingOperation {
        return ID3FrameStringContentParsingOperationFactory.make() { (content: String) in
            return (.RadioStationUrl, ID3FrameWithStringContent(content: content))
        }
    }
}
```

Which refers to `ID3FrameStringContentParsingOperation`:
```swift
class ID3FrameStringContentParsingOperation: FrameContentParsingOperation {
    private var stringContentParser: ID3FrameStringContentParser
    private var createFrameOperation: createFrameOperation

    init(stringContentParser: ID3FrameStringContentParser,
         assignToTagOperation: @escaping createFrameOperation) {
        self.stringContentParser = stringContentParser
        self.createFrameOperation = assignToTagOperation
    }

    func parse(frame: Data, version: ID3Version, completed: (FrameName, ID3Frame) -> ()) {
        if let frameContent = stringContentParser.parse(frame: frame, version: version) {
            let frameNameAndFrame = createFrameOperation(frameContent)
            completed(frameNameAndFrame.0, frameNameAndFrame.1)
        }
    }
}
```

and to `ID3FrameStringContentParsingOperationFactory`:
```swift
class ID3FrameStringContentParsingOperationFactory {
    static func make(operation: @escaping createFrameOperation) -> ID3FrameStringContentParsingOperation {
        let stringContentParser = ID3FrameStringContentParserFactory.make()
        return ID3FrameStringContentParsingOperation(stringContentParser: stringContentParser,
                                                     assignToTagOperation: operation)
    }
}
```

The first of those two refers to `ID3FrameStringContentParser`
```swift
class ID3FrameStringContentParser {
    private let stringEncodingDetector: ID3FrameStringEncodingDetector
    private let paddingRemover: PaddingRemover
    private let id3FrameConfiguration: ID3FrameConfiguration
    
    init(stringEncodingDetector: ID3FrameStringEncodingDetector,
         paddingRemover: PaddingRemover,
         id3FrameConfiguration: ID3FrameConfiguration) {
        self.stringEncodingDetector = stringEncodingDetector
        self.paddingRemover = paddingRemover
        self.id3FrameConfiguration = id3FrameConfiguration
    }
    
    func parse(frame: Data, version: ID3Version) -> String? {
        let headerSize = id3FrameConfiguration.headerSizeFor(version: version)
        let frameContentRangeStart = headerSize + id3FrameConfiguration.encodingSize()
        let frameContent = frame.subdata(in: frameContentRangeStart..<frame.count)
        let encoding = stringEncodingDetector.detect(frame: frame, version: version)
        if let frameContentAsString = String(data: frameContent, encoding: encoding) {
            return paddingRemover.removeFrom(string: frameContentAsString)
        } else {
            return nil
        }
    }
}
```
Which contains a reference to `ID3FrameStringEncodingDetector` and my antennae twitch at that because "encoding" seems to be the source of my problems today. So I look for that, which is as follows:

```swift
class ID3FrameStringEncodingDetector {
    private let id3FrameConfiguration: ID3FrameConfiguration
    private let id3StringEncodingConverter: ID3StringEncodingConverter
    
    init(id3FrameConfiguration: ID3FrameConfiguration,
         id3StringEncodingConverter: ID3StringEncodingConverter) {
        self.id3FrameConfiguration = id3FrameConfiguration
        self.id3StringEncodingConverter = id3StringEncodingConverter
    }
    
    func detect(frame: Data, version: ID3Version) -> String.Encoding {
        let encodingBytePosition = id3FrameConfiguration.encodingPositionFor(version: version)
        let encoding = id3StringEncodingConverter.convert(
            id3Encoding: ID3StringEncoding(rawValue: frame[encodingBytePosition]),
            version: version
        )
        return encoding
    }
}
```

which in turn leads me to...

```swift
class ID3StringEncodingConverter {
    
    func convert(id3Encoding: ID3StringEncoding?, version: ID3Version) -> String.Encoding {
        if let validId3Encoding = id3Encoding,
            validId3Encoding.exists(in: version) {
            return validId3Encoding.standardLibraryEncoding
        }
        return .isoLatin1
    }
}
```

Which...ah ha! Finally there's a place where I can change the actual encoding. Except that I don't dare touch any of it because I don't understand how it all fits together.

I've added `.ascii` to the `standardLibraryEncoding` enum but that's about as far as I've dared go?

**Comment by SDGGiesbrecht** [comment]
It’s reading the “h” in as the encoding byte. You need to make it not check for an encoding. This is all in the `parse(frame:version:)` method.

**Comment by NCrusher74** [comment]
Okay, there are a number of classes and types with `parse` methods. I think the one in `ID3FrameStringContentParser` is the one I need, correct?

**Comment by SDGGiesbrecht** [comment]
Yes. Although if it is the same type used for the other frames, then you need to make the change to a separate new one.

**Comment by NCrusher74** [comment]
Yeah. I looked at it for a while but couldn't figure out how to write it so that it would include the encoding check for one type of frame but not for another, so I'm making a `ID3FrameURLStringContentParser` class which will be referenced from a `ID3FrameURLStringContentParsingOperation` class that the UrlFrameContentParsingOperationFactory types will used instead of `ID3FrameStringContentParsingOperation`.

Is this what I should be doing?

```swift
class ID3FrameURLStringContentParser {
    private let paddingRemover: PaddingRemover
    private let id3FrameConfiguration: ID3FrameConfiguration
    
    init(paddingRemover: PaddingRemover,
         id3FrameConfiguration: ID3FrameConfiguration) {
        self.paddingRemover = paddingRemover
        self.id3FrameConfiguration = id3FrameConfiguration
    }
    
    func parse(frame: Data, version: ID3Version) -> String? {
        let headerSize = id3FrameConfiguration.headerSizeFor(version: version)
        let frameContentRangeStart = headerSize
        let frameContent = frame.subdata(in: frameContentRangeStart..<frame.count)
        if let frameContentAsString = String(data: data, encoding: ID3StringEncoding.ascii) {
            return paddingRemover.removeFrom(string: frameContentAsString)
        } else {
            return nil
        }
    }
}
```

**Pull request merged**
